# Install NGINX webserver
---
- name: "Install NGINX"
  hosts: all
  user: ubuntu
  become: true

  tasks:
  - name: install NGINX and LUA webserver scripting language
    apt:
      name:
        - nginx
        - lua-nginx-websocket
        - lua-nginx-string
      state: latest
      update_cache: yes

  - name: replace default configuration
    template: src=nginx.j2 dest=/etc/nginx/nginx.conf

  - name: send tm configuration
    template: src=nginx-tm.j2 dest=/etc/nginx/conf.d/time-management.conf

  - name: reload nginx configuration
    service: name=nginx state=reloaded
