# Install Docker from ubuntu repo
---
- name: "Install docker"
  hosts: all
  user: ubuntu
  become: true

  tasks:
  - name: "copy docker repository"
    copy: src=../files/docker.list dest=/etc/apt/sources.list.d/docker.list owner=root group=root

  #- name: "update kernel to latest version"
  #  yum: name=kernel state=latest

  - name: "load repository gpg key"
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --yes --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

  - name: "install prerequisites"
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release

  - name: "install docker"
    apt: 
      name: docker-ce
      state: latest
      update_cache: yes

  - name: "start and enable docker service"
    service: name=docker state=restarted enabled=yes
